ALTER TABLE answer_types CHARACTER SET latin1;
ALTER TABLE answer_values CHARACTER SET latin1;
ALTER TABLE dependencies CHARACTER SET latin1;
ALTER TABLE ip_track CHARACTER SET latin1;
ALTER TABLE questions CHARACTER SET latin1;
ALTER TABLE results_text CHARACTER SET latin1;
ALTER TABLE surveys CHARACTER SET latin1;
ALTER TABLE users CHARACTER SET latin1;